[package]
name = "login"
version = "0.1.0"
edition = "2024"

[dependencies]
authentication = { path = "../authentication" }
util = { path = "../../util" }
uuid = { version = "1", features = ["v4", "serde"] }