[package]
name = "authentication"
version = "0.1.0"
edition = "2024"

[dependencies]
util = { path = "../../util" }
bcrypt = "0"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
bimap = "0"