[package]
name = "shared_data"
version = "0.1.0"
edition = "2024"

[dependencies]
util = { path = "../../util" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crc32fast = "1"
byteorder = "1"
uuid = { version = "1", features = ["v4"] }